# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.9.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QGroupBox,
    QLabel, QLineEdit, QListWidget, QListWidgetItem,
    QPushButton, QRadioButton, QSizePolicy, QSpinBox,
    QStackedWidget, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(988, 600)
        font = QFont()
        font.setFamilies([u"FiraMono Nerd Font"])
        font.setPointSize(12)
        Form.setFont(font)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet(u"background-color: #0c1017;")
        self.menu_widget = QWidget(Form)
        self.menu_widget.setObjectName(u"menu_widget")
        self.menu_widget.setGeometry(QRect(5, -1, 201, 601))
        self.menu_lbl = QLabel(self.menu_widget)
        self.menu_lbl.setObjectName(u"menu_lbl")
        self.menu_lbl.setGeometry(QRect(6, 9, 191, 41))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_lbl.sizePolicy().hasHeightForWidth())
        self.menu_lbl.setSizePolicy(sizePolicy)
        self.menu_lbl.setBaseSize(QSize(0, 0))
        self.menu_lbl.setFont(font)
        self.menu_lbl.setStyleSheet(u"color: white;")
        self.menu_lbl.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.spaced_repetition_btn = QPushButton(self.menu_widget)
        self.spaced_repetition_btn.setObjectName(u"spaced_repetition_btn")
        self.spaced_repetition_btn.setGeometry(QRect(0, 400, 201, 51))
        font1 = QFont()
        font1.setFamilies([u"FiraMono Nerd Font"])
        font1.setPointSize(11)
        self.spaced_repetition_btn.setFont(font1)
        self.spaced_repetition_btn.setStyleSheet(u"background-color: rgb(47, 47, 47); color: white;")
        self.spaced_repetition_btn.setCheckable(True)
        self.spaced_repetition_btn.setAutoExclusive(True)
        self.active_recall_btn = QPushButton(self.menu_widget)
        self.active_recall_btn.setObjectName(u"active_recall_btn")
        self.active_recall_btn.setGeometry(QRect(0, 350, 201, 51))
        self.active_recall_btn.setFont(font1)
        self.active_recall_btn.setStyleSheet(u"background-color: rgb(47, 47, 47); color: white;")
        self.active_recall_btn.setCheckable(True)
        self.active_recall_btn.setAutoExclusive(True)
        self.incremental_reading_btn = QPushButton(self.menu_widget)
        self.incremental_reading_btn.setObjectName(u"incremental_reading_btn")
        self.incremental_reading_btn.setGeometry(QRect(0, 300, 201, 51))
        self.incremental_reading_btn.setFont(font1)
        self.incremental_reading_btn.setStyleSheet(u"background-color: rgb(47, 47, 47); color: white;")
        self.incremental_reading_btn.setCheckable(True)
        self.incremental_reading_btn.setAutoExclusive(True)
        self.home_btn = QPushButton(self.menu_widget)
        self.home_btn.setObjectName(u"home_btn")
        self.home_btn.setGeometry(QRect(0, 50, 201, 51))
        self.home_btn.setFont(font1)
        self.home_btn.setStyleSheet(u"background-color: rgb(47, 47, 47); color: white;")
        self.home_btn.setCheckable(True)
        self.home_btn.setAutoExclusive(True)
        self.pomodoro_btn = QPushButton(self.menu_widget)
        self.pomodoro_btn.setObjectName(u"pomodoro_btn")
        self.pomodoro_btn.setGeometry(QRect(0, 150, 201, 51))
        self.pomodoro_btn.setFont(font1)
        self.pomodoro_btn.setStyleSheet(u"background-color: rgb(47, 47, 47); color: white;")
        self.pomodoro_btn.setCheckable(True)
        self.pomodoro_btn.setAutoExclusive(True)
        self.quiz_btn = QPushButton(self.menu_widget)
        self.quiz_btn.setObjectName(u"quiz_btn")
        self.quiz_btn.setGeometry(QRect(0, 200, 201, 51))
        self.quiz_btn.setFont(font1)
        self.quiz_btn.setStyleSheet(u"background-color: rgb(47, 47, 47); color: white;")
        self.quiz_btn.setCheckable(True)
        self.quiz_btn.setAutoExclusive(True)
        self.second_brain_btn = QPushButton(self.menu_widget)
        self.second_brain_btn.setObjectName(u"second_brain_btn")
        self.second_brain_btn.setGeometry(QRect(0, 250, 201, 51))
        self.second_brain_btn.setFont(font1)
        self.second_brain_btn.setStyleSheet(u"background-color: rgb(47, 47, 47); color: white;")
        self.second_brain_btn.setCheckable(True)
        self.second_brain_btn.setAutoExclusive(True)
        self.to_do_btn = QPushButton(self.menu_widget)
        self.to_do_btn.setObjectName(u"to_do_btn")
        self.to_do_btn.setGeometry(QRect(0, 100, 201, 51))
        self.to_do_btn.setFont(font1)
        self.to_do_btn.setStyleSheet(u"background-color: rgb(47, 47, 47); color: white;")
        self.to_do_btn.setCheckable(True)
        self.to_do_btn.setAutoExclusive(True)
        self.login_menu = QStackedWidget(Form)
        self.login_menu.setObjectName(u"login_menu")
        self.login_menu.setGeometry(QRect(210, 0, 811, 61))
        self.logged_out_widget = QWidget()
        self.logged_out_widget.setObjectName(u"logged_out_widget")
        self.sign_in_out_btn = QPushButton(self.logged_out_widget)
        self.sign_in_out_btn.setObjectName(u"sign_in_out_btn")
        self.sign_in_out_btn.setGeometry(QRect(500, 10, 231, 51))
        self.sign_in_out_btn.setFont(font1)
        self.sign_in_out_btn.setStyleSheet(u"background-color: rgb(47, 47, 47); color: white;")
        self.sign_in_out_btn.setCheckable(True)
        self.sign_in_out_btn.setAutoExclusive(True)
        self.login_menu.addWidget(self.logged_out_widget)
        self.logged_in_widget = QWidget()
        self.logged_in_widget.setObjectName(u"logged_in_widget")
        self.log_out_btn = QPushButton(self.logged_in_widget)
        self.log_out_btn.setObjectName(u"log_out_btn")
        self.log_out_btn.setGeometry(QRect(510, 10, 111, 51))
        self.log_out_btn.setFont(font1)
        self.log_out_btn.setStyleSheet(u"background-color: rgb(47, 47, 47); color: white;")
        self.log_out_btn.setCheckable(True)
        self.log_out_btn.setAutoExclusive(True)
        self.profile_btn = QPushButton(self.logged_in_widget)
        self.profile_btn.setObjectName(u"profile_btn")
        self.profile_btn.setGeometry(QRect(630, 10, 111, 51))
        self.profile_btn.setFont(font1)
        self.profile_btn.setStyleSheet(u"background-color: rgb(47, 47, 47); color: white;")
        self.profile_btn.setCheckable(True)
        self.profile_btn.setAutoExclusive(True)
        self.login_menu.addWidget(self.logged_in_widget)
        self.main_widget = QStackedWidget(Form)
        self.main_widget.setObjectName(u"main_widget")
        self.main_widget.setGeometry(QRect(210, 80, 811, 511))
        self.sign_up_in_widget = QWidget()
        self.sign_up_in_widget.setObjectName(u"sign_up_in_widget")
        self.username_up_lbl = QLabel(self.sign_up_in_widget)
        self.username_up_lbl.setObjectName(u"username_up_lbl")
        self.username_up_lbl.setGeometry(QRect(40, 100, 200, 25))
        self.username_up_lbl.setFont(font)
        self.username_up_lbl.setStyleSheet(u"color: white;")
        self.password_up_lbl = QLabel(self.sign_up_in_widget)
        self.password_up_lbl.setObjectName(u"password_up_lbl")
        self.password_up_lbl.setGeometry(QRect(40, 210, 200, 25))
        self.password_up_lbl.setFont(font)
        self.password_up_lbl.setStyleSheet(u"color: white;")
        self.sign_up_lbl = QLabel(self.sign_up_in_widget)
        self.sign_up_lbl.setObjectName(u"sign_up_lbl")
        self.sign_up_lbl.setGeometry(QRect(40, 30, 200, 31))
        font2 = QFont()
        font2.setFamilies([u"FiraMono Nerd Font"])
        font2.setPointSize(18)
        self.sign_up_lbl.setFont(font2)
        self.sign_up_lbl.setStyleSheet(u"color: white;")
        self.sign_up_lbl.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.sign_up_btn = QPushButton(self.sign_up_in_widget)
        self.sign_up_btn.setObjectName(u"sign_up_btn")
        self.sign_up_btn.setGeometry(QRect(40, 430, 231, 51))
        self.sign_up_btn.setFont(font1)
        self.sign_up_btn.setStyleSheet(u"background-color: rgb(47, 47, 47); color: white;")
        self.sign_up_btn.setCheckable(True)
        self.sign_up_btn.setAutoExclusive(True)
        self.username_up_input = QLineEdit(self.sign_up_in_widget)
        self.username_up_input.setObjectName(u"username_up_input")
        self.username_up_input.setGeometry(QRect(40, 150, 191, 27))
        self.password_up_input = QLineEdit(self.sign_up_in_widget)
        self.password_up_input.setObjectName(u"password_up_input")
        self.password_up_input.setGeometry(QRect(40, 260, 191, 27))
        self.confirm_password_input = QLineEdit(self.sign_up_in_widget)
        self.confirm_password_input.setObjectName(u"confirm_password_input")
        self.confirm_password_input.setGeometry(QRect(40, 370, 191, 27))
        self.confirm_password_lbl = QLabel(self.sign_up_in_widget)
        self.confirm_password_lbl.setObjectName(u"confirm_password_lbl")
        self.confirm_password_lbl.setGeometry(QRect(40, 320, 200, 25))
        self.confirm_password_lbl.setFont(font)
        self.confirm_password_lbl.setStyleSheet(u"color: white;")
        self.password_in_input = QLineEdit(self.sign_up_in_widget)
        self.password_in_input.setObjectName(u"password_in_input")
        self.password_in_input.setGeometry(QRect(500, 260, 191, 27))
        self.sign_in_lbl = QLabel(self.sign_up_in_widget)
        self.sign_in_lbl.setObjectName(u"sign_in_lbl")
        self.sign_in_lbl.setGeometry(QRect(500, 30, 200, 31))
        self.sign_in_lbl.setFont(font2)
        self.sign_in_lbl.setStyleSheet(u"color: white;")
        self.sign_in_lbl.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.username_in_input = QLineEdit(self.sign_up_in_widget)
        self.username_in_input.setObjectName(u"username_in_input")
        self.username_in_input.setGeometry(QRect(500, 150, 191, 27))
        self.username_in_lbl = QLabel(self.sign_up_in_widget)
        self.username_in_lbl.setObjectName(u"username_in_lbl")
        self.username_in_lbl.setGeometry(QRect(500, 100, 200, 25))
        self.username_in_lbl.setFont(font)
        self.username_in_lbl.setStyleSheet(u"color: white;")
        self.sign_in_btn = QPushButton(self.sign_up_in_widget)
        self.sign_in_btn.setObjectName(u"sign_in_btn")
        self.sign_in_btn.setGeometry(QRect(500, 430, 231, 51))
        self.sign_in_btn.setFont(font1)
        self.sign_in_btn.setStyleSheet(u"background-color: rgb(47, 47, 47); color: white;")
        self.sign_in_btn.setCheckable(True)
        self.sign_in_btn.setAutoExclusive(True)
        self.password_in_lb = QLabel(self.sign_up_in_widget)
        self.password_in_lb.setObjectName(u"password_in_lb")
        self.password_in_lb.setGeometry(QRect(500, 210, 200, 25))
        self.password_in_lb.setFont(font)
        self.password_in_lb.setStyleSheet(u"color: white;")
        self.stay_logged_cb = QCheckBox(self.sign_up_in_widget)
        self.stay_logged_cb.setObjectName(u"stay_logged_cb")
        self.stay_logged_cb.setGeometry(QRect(500, 320, 191, 25))
        self.main_widget.addWidget(self.sign_up_in_widget)
        self.todo_widget = QWidget()
        self.todo_widget.setObjectName(u"todo_widget")
        self.add_item_lbl = QLabel(self.todo_widget)
        self.add_item_lbl.setObjectName(u"add_item_lbl")
        self.add_item_lbl.setGeometry(QRect(40, 30, 121, 25))
        self.add_item_lbl.setFont(font2)
        self.add_item_lbl.setStyleSheet(u"color: white;")
        self.add_item_btn = QPushButton(self.todo_widget)
        self.add_item_btn.setObjectName(u"add_item_btn")
        self.add_item_btn.setGeometry(QRect(40, 430, 261, 51))
        self.add_item_btn.setFont(font1)
        self.add_item_btn.setStyleSheet(u"background-color: rgb(47, 47, 47); color: white;")
        self.add_item_btn.setCheckable(True)
        self.add_item_btn.setAutoExclusive(True)
        self.item_txt = QLineEdit(self.todo_widget)
        self.item_txt.setObjectName(u"item_txt")
        self.item_txt.setGeometry(QRect(40, 120, 261, 241))
        self.item_txt.setFont(font)
        self.priority_spinbox = QSpinBox(self.todo_widget)
        self.priority_spinbox.setObjectName(u"priority_spinbox")
        self.priority_spinbox.setGeometry(QRect(153, 380, 141, 27))
        self.priority_spinbox.setFont(font)
        self.item_txt_lbl = QLabel(self.todo_widget)
        self.item_txt_lbl.setObjectName(u"item_txt_lbl")
        self.item_txt_lbl.setGeometry(QRect(40, 80, 161, 25))
        self.item_txt_lbl.setFont(font)
        self.item_txt_lbl.setStyleSheet(u"color: white;")
        self.priority_lbl = QLabel(self.todo_widget)
        self.priority_lbl.setObjectName(u"priority_lbl")
        self.priority_lbl.setGeometry(QRect(40, 380, 91, 25))
        self.priority_lbl.setFont(font)
        self.priority_lbl.setStyleSheet(u"color: white;")
        self.todo_listwidget = QListWidget(self.todo_widget)
        self.todo_listwidget.setObjectName(u"todo_listwidget")
        self.todo_listwidget.setGeometry(QRect(380, 30, 361, 451))
        self.main_widget.addWidget(self.todo_widget)
        self.quiz_widget = QWidget()
        self.quiz_widget.setObjectName(u"quiz_widget")
        self.quiz_stacked_widget = QStackedWidget(self.quiz_widget)
        self.quiz_stacked_widget.setObjectName(u"quiz_stacked_widget")
        self.quiz_stacked_widget.setGeometry(QRect(0, 0, 811, 511))
        self.params_widget = QWidget()
        self.params_widget.setObjectName(u"params_widget")
        self.param_lbl = QLabel(self.params_widget)
        self.param_lbl.setObjectName(u"param_lbl")
        self.param_lbl.setGeometry(QRect(40, 30, 701, 31))
        sizePolicy.setHeightForWidth(self.param_lbl.sizePolicy().hasHeightForWidth())
        self.param_lbl.setSizePolicy(sizePolicy)
        self.param_lbl.setBaseSize(QSize(0, 0))
        self.param_lbl.setFont(font2)
        self.param_lbl.setStyleSheet(u"color: white;")
        self.param_lbl.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.file_lbl = QLabel(self.params_widget)
        self.file_lbl.setObjectName(u"file_lbl")
        self.file_lbl.setGeometry(QRect(40, 100, 250, 25))
        sizePolicy.setHeightForWidth(self.file_lbl.sizePolicy().hasHeightForWidth())
        self.file_lbl.setSizePolicy(sizePolicy)
        self.file_lbl.setBaseSize(QSize(0, 0))
        self.file_lbl.setFont(font)
        self.file_lbl.setStyleSheet(u"color: white;")
        self.file_lbl.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.score_lbl = QLabel(self.params_widget)
        self.score_lbl.setObjectName(u"score_lbl")
        self.score_lbl.setGeometry(QRect(40, 220, 250, 25))
        sizePolicy.setHeightForWidth(self.score_lbl.sizePolicy().hasHeightForWidth())
        self.score_lbl.setSizePolicy(sizePolicy)
        self.score_lbl.setBaseSize(QSize(0, 0))
        self.score_lbl.setFont(font)
        self.score_lbl.setStyleSheet(u"color: white;")
        self.score_lbl.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.answer_lbl = QLabel(self.params_widget)
        self.answer_lbl.setObjectName(u"answer_lbl")
        self.answer_lbl.setGeometry(QRect(490, 340, 250, 25))
        sizePolicy.setHeightForWidth(self.answer_lbl.sizePolicy().hasHeightForWidth())
        self.answer_lbl.setSizePolicy(sizePolicy)
        self.answer_lbl.setBaseSize(QSize(0, 0))
        self.answer_lbl.setFont(font)
        self.answer_lbl.setStyleSheet(u"color: white;")
        self.answer_lbl.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.random_q_order_lbl = QLabel(self.params_widget)
        self.random_q_order_lbl.setObjectName(u"random_q_order_lbl")
        self.random_q_order_lbl.setGeometry(QRect(490, 220, 251, 25))
        sizePolicy.setHeightForWidth(self.random_q_order_lbl.sizePolicy().hasHeightForWidth())
        self.random_q_order_lbl.setSizePolicy(sizePolicy)
        self.random_q_order_lbl.setBaseSize(QSize(0, 0))
        self.random_q_order_lbl.setFont(font)
        self.random_q_order_lbl.setStyleSheet(u"color: white;")
        self.random_q_order_lbl.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.random_ans_order_lbl = QLabel(self.params_widget)
        self.random_ans_order_lbl.setObjectName(u"random_ans_order_lbl")
        self.random_ans_order_lbl.setGeometry(QRect(490, 100, 251, 25))
        sizePolicy.setHeightForWidth(self.random_ans_order_lbl.sizePolicy().hasHeightForWidth())
        self.random_ans_order_lbl.setSizePolicy(sizePolicy)
        self.random_ans_order_lbl.setBaseSize(QSize(0, 0))
        self.random_ans_order_lbl.setFont(font)
        self.random_ans_order_lbl.setStyleSheet(u"color: white;")
        self.random_ans_order_lbl.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.file_input = QComboBox(self.params_widget)
        self.file_input.setObjectName(u"file_input")
        self.file_input.setGeometry(QRect(40, 150, 281, 31))
        self.file_input.setStyleSheet(u"color: White;")
        self.file_input.setEditable(True)
        self.rqo_gb = QGroupBox(self.params_widget)
        self.rqo_gb.setObjectName(u"rqo_gb")
        self.rqo_gb.setGeometry(QRect(490, 250, 241, 41))
        self.rqoy_rbtn = QRadioButton(self.rqo_gb)
        self.rqoy_rbtn.setObjectName(u"rqoy_rbtn")
        self.rqoy_rbtn.setGeometry(QRect(10, 10, 50, 25))
        self.rqoy_rbtn.setStyleSheet(u"color:white;")
        self.rqoy_rbtn.setChecked(True)
        self.rqon_rbtn = QRadioButton(self.rqo_gb)
        self.rqon_rbtn.setObjectName(u"rqon_rbtn")
        self.rqon_rbtn.setGeometry(QRect(180, 10, 50, 25))
        self.rqon_rbtn.setStyleSheet(u"color:white;")
        self.rao_gb = QGroupBox(self.params_widget)
        self.rao_gb.setObjectName(u"rao_gb")
        self.rao_gb.setGeometry(QRect(490, 130, 241, 41))
        self.raoy_rbtn = QRadioButton(self.rao_gb)
        self.raoy_rbtn.setObjectName(u"raoy_rbtn")
        self.raoy_rbtn.setGeometry(QRect(10, 10, 50, 25))
        self.raoy_rbtn.setStyleSheet(u"color:white;")
        self.raoy_rbtn.setChecked(True)
        self.raon_rbtn = QRadioButton(self.rao_gb)
        self.raon_rbtn.setObjectName(u"raon_rbtn")
        self.raon_rbtn.setGeometry(QRect(180, 10, 50, 25))
        self.raon_rbtn.setStyleSheet(u"color:white;")
        self.sc_gb = QGroupBox(self.params_widget)
        self.sc_gb.setObjectName(u"sc_gb")
        self.sc_gb.setGeometry(QRect(40, 250, 361, 41))
        self.aeq_rbtn = QRadioButton(self.sc_gb)
        self.aeq_rbtn.setObjectName(u"aeq_rbtn")
        self.aeq_rbtn.setGeometry(QRect(10, 10, 151, 25))
        self.aeq_rbtn.setStyleSheet(u"color:white;")
        self.ate_rbtn = QRadioButton(self.sc_gb)
        self.ate_rbtn.setObjectName(u"ate_rbtn")
        self.ate_rbtn.setGeometry(QRect(220, 10, 131, 25))
        self.ate_rbtn.setStyleSheet(u"color:white;")
        self.ate_rbtn.setChecked(True)
        self.groupBox = QGroupBox(self.params_widget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(490, 370, 241, 41))
        self.say_rbtn = QRadioButton(self.groupBox)
        self.say_rbtn.setObjectName(u"say_rbtn")
        self.say_rbtn.setGeometry(QRect(10, 10, 50, 25))
        self.say_rbtn.setStyleSheet(u"color:white;")
        self.say_rbtn.setChecked(True)
        self.san_rbtn = QRadioButton(self.groupBox)
        self.san_rbtn.setObjectName(u"san_rbtn")
        self.san_rbtn.setGeometry(QRect(180, 10, 50, 25))
        self.san_rbtn.setStyleSheet(u"color:white;")
        self.browse_file_btn = QPushButton(self.params_widget)
        self.browse_file_btn.setObjectName(u"browse_file_btn")
        self.browse_file_btn.setGeometry(QRect(350, 150, 51, 31))
        self.quiz_stacked_widget.addWidget(self.params_widget)
        self.question_widget = QWidget()
        self.question_widget.setObjectName(u"question_widget")
        self.quiz_stacked_widget.addWidget(self.question_widget)
        self.main_widget.addWidget(self.quiz_widget)
        self.home_widget = QWidget()
        self.home_widget.setObjectName(u"home_widget")
        self.overall_activity_lbl = QLabel(self.home_widget)
        self.overall_activity_lbl.setObjectName(u"overall_activity_lbl")
        self.overall_activity_lbl.setGeometry(QRect(20, 30, 200, 25))
        self.overall_activity_lbl.setFont(font)
        self.overall_activity_lbl.setStyleSheet(u"color: white;")
        self.week_activity_lbl = QLabel(self.home_widget)
        self.week_activity_lbl.setObjectName(u"week_activity_lbl")
        self.week_activity_lbl.setGeometry(QRect(20, 280, 200, 25))
        sizePolicy.setHeightForWidth(self.week_activity_lbl.sizePolicy().hasHeightForWidth())
        self.week_activity_lbl.setSizePolicy(sizePolicy)
        self.week_activity_lbl.setBaseSize(QSize(0, 0))
        self.week_activity_lbl.setFont(font)
        self.week_activity_lbl.setStyleSheet(u"color: white;")
        self.to_do_lbl = QLabel(self.home_widget)
        self.to_do_lbl.setObjectName(u"to_do_lbl")
        self.to_do_lbl.setGeometry(QRect(450, 280, 200, 25))
        self.to_do_lbl.setFont(font)
        self.to_do_lbl.setStyleSheet(u"color: white;")
        self.overall_activity_widget = QWidget(self.home_widget)
        self.overall_activity_widget.setObjectName(u"overall_activity_widget")
        self.overall_activity_widget.setGeometry(QRect(20, 70, 731, 180))
        self.week_activity_widget = QWidget(self.home_widget)
        self.week_activity_widget.setObjectName(u"week_activity_widget")
        self.week_activity_widget.setGeometry(QRect(20, 320, 391, 180))
        self.to_do_list_widget = QWidget(self.home_widget)
        self.to_do_list_widget.setObjectName(u"to_do_list_widget")
        self.to_do_list_widget.setGeometry(QRect(450, 320, 301, 171))
        self.main_widget.addWidget(self.home_widget)
        self.second_brain_widget = QWidget()
        self.second_brain_widget.setObjectName(u"second_brain_widget")
        self.main_widget.addWidget(self.second_brain_widget)
        self.spaced_repetition_widget = QWidget()
        self.spaced_repetition_widget.setObjectName(u"spaced_repetition_widget")
        self.main_widget.addWidget(self.spaced_repetition_widget)
        self.active_recall_widget = QWidget()
        self.active_recall_widget.setObjectName(u"active_recall_widget")
        self.main_widget.addWidget(self.active_recall_widget)
        self.incremental_reading_widget = QWidget()
        self.incremental_reading_widget.setObjectName(u"incremental_reading_widget")
        self.main_widget.addWidget(self.incremental_reading_widget)
        self.pomodoro_widget = QWidget()
        self.pomodoro_widget.setObjectName(u"pomodoro_widget")
        self.main_widget.addWidget(self.pomodoro_widget)

        self.retranslateUi(Form)

        self.main_widget.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Learning App", None))
        self.menu_lbl.setText(QCoreApplication.translate("Form", u"Strategies", None))
        self.spaced_repetition_btn.setText(QCoreApplication.translate("Form", u"Spaced Repetition", None))
        self.active_recall_btn.setText(QCoreApplication.translate("Form", u"Active Recall", None))
        self.incremental_reading_btn.setText(QCoreApplication.translate("Form", u"Incremental Reading", None))
        self.home_btn.setText(QCoreApplication.translate("Form", u"Home", None))
        self.pomodoro_btn.setText(QCoreApplication.translate("Form", u"Pomodoro", None))
        self.quiz_btn.setText(QCoreApplication.translate("Form", u"Quiz", None))
        self.second_brain_btn.setText(QCoreApplication.translate("Form", u"Second Brain", None))
        self.to_do_btn.setText(QCoreApplication.translate("Form", u"To-Do List", None))
        self.sign_in_out_btn.setText(QCoreApplication.translate("Form", u"Sign Up or Sign In", None))
        self.log_out_btn.setText(QCoreApplication.translate("Form", u"Log Out", None))
        self.profile_btn.setText(QCoreApplication.translate("Form", u"Profile", None))
        self.username_up_lbl.setText(QCoreApplication.translate("Form", u"Username", None))
        self.password_up_lbl.setText(QCoreApplication.translate("Form", u"Password", None))
        self.sign_up_lbl.setText(QCoreApplication.translate("Form", u"Sign Up", None))
        self.sign_up_btn.setText(QCoreApplication.translate("Form", u"Sign Up", None))
        self.confirm_password_lbl.setText(QCoreApplication.translate("Form", u"Confirm password", None))
        self.sign_in_lbl.setText(QCoreApplication.translate("Form", u"Sign In", None))
        self.username_in_lbl.setText(QCoreApplication.translate("Form", u"Username", None))
        self.sign_in_btn.setText(QCoreApplication.translate("Form", u"Sign In", None))
        self.password_in_lb.setText(QCoreApplication.translate("Form", u"Password", None))
        self.stay_logged_cb.setText(QCoreApplication.translate("Form", u"Stay logged", None))
        self.add_item_lbl.setText(QCoreApplication.translate("Form", u"Add item", None))
        self.add_item_btn.setText(QCoreApplication.translate("Form", u"Add", None))
        self.item_txt_lbl.setText(QCoreApplication.translate("Form", u"Item description:", None))
        self.priority_lbl.setText(QCoreApplication.translate("Form", u"Priority:", None))
        self.param_lbl.setText(QCoreApplication.translate("Form", u"Parameters", None))
        self.file_lbl.setText(QCoreApplication.translate("Form", u"File", None))
        self.score_lbl.setText(QCoreApplication.translate("Form", u"Show score", None))
        self.answer_lbl.setText(QCoreApplication.translate("Form", u"Show answer", None))
        self.random_q_order_lbl.setText(QCoreApplication.translate("Form", u"Randomized quesion order", None))
        self.random_ans_order_lbl.setText(QCoreApplication.translate("Form", u"Randomized answer order", None))
        self.rqo_gb.setTitle("")
        self.rqoy_rbtn.setText(QCoreApplication.translate("Form", u"Yes", None))
        self.rqon_rbtn.setText(QCoreApplication.translate("Form", u"No", None))
        self.rao_gb.setTitle("")
        self.raoy_rbtn.setText(QCoreApplication.translate("Form", u"Yes", None))
        self.raon_rbtn.setText(QCoreApplication.translate("Form", u"No", None))
        self.sc_gb.setTitle("")
        self.aeq_rbtn.setText(QCoreApplication.translate("Form", u"After each question", None))
        self.ate_rbtn.setText(QCoreApplication.translate("Form", u"At the end only", None))
        self.groupBox.setTitle("")
        self.say_rbtn.setText(QCoreApplication.translate("Form", u"Yes", None))
        self.san_rbtn.setText(QCoreApplication.translate("Form", u"No", None))
        self.browse_file_btn.setText(QCoreApplication.translate("Form", u"...", None))
        self.overall_activity_lbl.setText(QCoreApplication.translate("Form", u"Overall Activity", None))
        self.week_activity_lbl.setText(QCoreApplication.translate("Form", u"This Week Activity", None))
        self.to_do_lbl.setText(QCoreApplication.translate("Form", u"To-Do List", None))
    # retranslateUi

