# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.9.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (
    QCoreApplication,
    QMetaObject,
    QRect,
    QSize,
    Qt,
)
from PySide6.QtGui import (
    QFont,
)
from PySide6.QtWidgets import (
    QCheckBox,
    QComboBox,
    QLabel,
    QLineEdit,
    QListWidget,
    QPushButton,
    QRadioButton,
    QSizePolicy,
    QSpinBox,
    QStackedWidget,
    QWidget,
)


class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName("Form")
        Form.resize(988, 600)
        font = QFont()
        font.setFamilies(["FiraMono Nerd Font"])
        font.setPointSize(12)
        Form.setFont(font)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("background-color: #0c1017;")
        self.menu_widget = QWidget(Form)
        self.menu_widget.setObjectName("menu_widget")
        self.menu_widget.setGeometry(QRect(5, -1, 201, 601))
        self.menu_lbl = QLabel(self.menu_widget)
        self.menu_lbl.setObjectName("menu_lbl")
        self.menu_lbl.setGeometry(QRect(6, 9, 191, 41))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_lbl.sizePolicy().hasHeightForWidth())
        self.menu_lbl.setSizePolicy(sizePolicy)
        self.menu_lbl.setBaseSize(QSize(0, 0))
        self.menu_lbl.setFont(font)
        self.menu_lbl.setStyleSheet("color: white;")
        self.menu_lbl.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.spaced_repetition_btn = QPushButton(self.menu_widget)
        self.spaced_repetition_btn.setObjectName("spaced_repetition_btn")
        self.spaced_repetition_btn.setGeometry(QRect(0, 400, 201, 51))
        font1 = QFont()
        font1.setFamilies(["FiraMono Nerd Font"])
        font1.setPointSize(11)
        self.spaced_repetition_btn.setFont(font1)
        self.spaced_repetition_btn.setStyleSheet(
            "background-color: rgb(47, 47, 47); color: white;"
        )
        self.spaced_repetition_btn.setCheckable(True)
        self.spaced_repetition_btn.setAutoExclusive(True)
        self.active_recall_btn = QPushButton(self.menu_widget)
        self.active_recall_btn.setObjectName("active_recall_btn")
        self.active_recall_btn.setGeometry(QRect(0, 350, 201, 51))
        self.active_recall_btn.setFont(font1)
        self.active_recall_btn.setStyleSheet(
            "background-color: rgb(47, 47, 47); color: white;"
        )
        self.active_recall_btn.setCheckable(True)
        self.active_recall_btn.setAutoExclusive(True)
        self.incremental_reading_btn = QPushButton(self.menu_widget)
        self.incremental_reading_btn.setObjectName("incremental_reading_btn")
        self.incremental_reading_btn.setGeometry(QRect(0, 300, 201, 51))
        self.incremental_reading_btn.setFont(font1)
        self.incremental_reading_btn.setStyleSheet(
            "background-color: rgb(47, 47, 47); color: white;"
        )
        self.incremental_reading_btn.setCheckable(True)
        self.incremental_reading_btn.setAutoExclusive(True)
        self.home_btn = QPushButton(self.menu_widget)
        self.home_btn.setObjectName("home_btn")
        self.home_btn.setGeometry(QRect(0, 50, 201, 51))
        self.home_btn.setFont(font1)
        self.home_btn.setStyleSheet("background-color: rgb(47, 47, 47); color: white;")
        self.home_btn.setCheckable(True)
        self.home_btn.setAutoExclusive(True)
        self.pomodoro_btn = QPushButton(self.menu_widget)
        self.pomodoro_btn.setObjectName("pomodoro_btn")
        self.pomodoro_btn.setGeometry(QRect(0, 150, 201, 51))
        self.pomodoro_btn.setFont(font1)
        self.pomodoro_btn.setStyleSheet(
            "background-color: rgb(47, 47, 47); color: white;"
        )
        self.pomodoro_btn.setCheckable(True)
        self.pomodoro_btn.setAutoExclusive(True)
        self.quiz_btn = QPushButton(self.menu_widget)
        self.quiz_btn.setObjectName("quiz_btn")
        self.quiz_btn.setGeometry(QRect(0, 200, 201, 51))
        self.quiz_btn.setFont(font1)
        self.quiz_btn.setStyleSheet("background-color: rgb(47, 47, 47); color: white;")
        self.quiz_btn.setCheckable(True)
        self.quiz_btn.setAutoExclusive(True)
        self.second_brain_btn = QPushButton(self.menu_widget)
        self.second_brain_btn.setObjectName("second_brain_btn")
        self.second_brain_btn.setGeometry(QRect(0, 250, 201, 51))
        self.second_brain_btn.setFont(font1)
        self.second_brain_btn.setStyleSheet(
            "background-color: rgb(47, 47, 47); color: white;"
        )
        self.second_brain_btn.setCheckable(True)
        self.second_brain_btn.setAutoExclusive(True)
        self.to_do_btn = QPushButton(self.menu_widget)
        self.to_do_btn.setObjectName("to_do_btn")
        self.to_do_btn.setGeometry(QRect(0, 100, 201, 51))
        self.to_do_btn.setFont(font1)
        self.to_do_btn.setStyleSheet("background-color: rgb(47, 47, 47); color: white;")
        self.to_do_btn.setCheckable(True)
        self.to_do_btn.setAutoExclusive(True)
        self.login_menu = QStackedWidget(Form)
        self.login_menu.setObjectName("login_menu")
        self.login_menu.setGeometry(QRect(210, 0, 811, 61))
        self.logged_out_widget = QWidget()
        self.logged_out_widget.setObjectName("logged_out_widget")
        self.sign_in_out_btn = QPushButton(self.logged_out_widget)
        self.sign_in_out_btn.setObjectName("sign_in_out_btn")
        self.sign_in_out_btn.setGeometry(QRect(500, 10, 231, 51))
        self.sign_in_out_btn.setFont(font1)
        self.sign_in_out_btn.setStyleSheet(
            "background-color: rgb(47, 47, 47); color: white;"
        )
        self.sign_in_out_btn.setCheckable(True)
        self.sign_in_out_btn.setAutoExclusive(True)
        self.login_menu.addWidget(self.logged_out_widget)
        self.logged_in_widget = QWidget()
        self.logged_in_widget.setObjectName("logged_in_widget")
        self.log_out_btn = QPushButton(self.logged_in_widget)
        self.log_out_btn.setObjectName("log_out_btn")
        self.log_out_btn.setGeometry(QRect(510, 10, 111, 51))
        self.log_out_btn.setFont(font1)
        self.log_out_btn.setStyleSheet(
            "background-color: rgb(47, 47, 47); color: white;"
        )
        self.log_out_btn.setCheckable(True)
        self.log_out_btn.setAutoExclusive(True)
        self.profile_btn = QPushButton(self.logged_in_widget)
        self.profile_btn.setObjectName("profile_btn")
        self.profile_btn.setGeometry(QRect(630, 10, 111, 51))
        self.profile_btn.setFont(font1)
        self.profile_btn.setStyleSheet(
            "background-color: rgb(47, 47, 47); color: white;"
        )
        self.profile_btn.setCheckable(True)
        self.profile_btn.setAutoExclusive(True)
        self.login_menu.addWidget(self.logged_in_widget)
        self.main_widget = QStackedWidget(Form)
        self.main_widget.setObjectName("main_widget")
        self.main_widget.setGeometry(QRect(210, 80, 811, 511))
        self.sign_up_in_widget = QWidget()
        self.sign_up_in_widget.setObjectName("sign_up_in_widget")
        self.username_up_lbl = QLabel(self.sign_up_in_widget)
        self.username_up_lbl.setObjectName("username_up_lbl")
        self.username_up_lbl.setGeometry(QRect(40, 100, 200, 25))
        self.username_up_lbl.setFont(font)
        self.username_up_lbl.setStyleSheet("color: white;")
        self.password_up_lbl = QLabel(self.sign_up_in_widget)
        self.password_up_lbl.setObjectName("password_up_lbl")
        self.password_up_lbl.setGeometry(QRect(40, 210, 200, 25))
        self.password_up_lbl.setFont(font)
        self.password_up_lbl.setStyleSheet("color: white;")
        self.sign_up_lbl = QLabel(self.sign_up_in_widget)
        self.sign_up_lbl.setObjectName("sign_up_lbl")
        self.sign_up_lbl.setGeometry(QRect(40, 30, 200, 31))
        font2 = QFont()
        font2.setFamilies(["FiraMono Nerd Font"])
        font2.setPointSize(18)
        self.sign_up_lbl.setFont(font2)
        self.sign_up_lbl.setStyleSheet("color: white;")
        self.sign_up_lbl.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.sign_up_btn = QPushButton(self.sign_up_in_widget)
        self.sign_up_btn.setObjectName("sign_up_btn")
        self.sign_up_btn.setGeometry(QRect(40, 430, 231, 51))
        self.sign_up_btn.setFont(font1)
        self.sign_up_btn.setStyleSheet(
            "background-color: rgb(47, 47, 47); color: white;"
        )
        self.sign_up_btn.setCheckable(True)
        self.sign_up_btn.setAutoExclusive(True)
        self.username_up_input = QLineEdit(self.sign_up_in_widget)
        self.username_up_input.setObjectName("username_up_input")
        self.username_up_input.setGeometry(QRect(40, 150, 191, 27))
        self.password_up_input = QLineEdit(self.sign_up_in_widget)
        self.password_up_input.setObjectName("password_up_input")
        self.password_up_input.setGeometry(QRect(40, 260, 191, 27))
        self.confirm_password_input = QLineEdit(self.sign_up_in_widget)
        self.confirm_password_input.setObjectName("confirm_password_input")
        self.confirm_password_input.setGeometry(QRect(40, 370, 191, 27))
        self.confirm_password_lbl = QLabel(self.sign_up_in_widget)
        self.confirm_password_lbl.setObjectName("confirm_password_lbl")
        self.confirm_password_lbl.setGeometry(QRect(40, 320, 200, 25))
        self.confirm_password_lbl.setFont(font)
        self.confirm_password_lbl.setStyleSheet("color: white;")
        self.password_in_input = QLineEdit(self.sign_up_in_widget)
        self.password_in_input.setObjectName("password_in_input")
        self.password_in_input.setGeometry(QRect(500, 260, 191, 27))
        self.sign_in_lbl = QLabel(self.sign_up_in_widget)
        self.sign_in_lbl.setObjectName("sign_in_lbl")
        self.sign_in_lbl.setGeometry(QRect(500, 30, 200, 31))
        self.sign_in_lbl.setFont(font2)
        self.sign_in_lbl.setStyleSheet("color: white;")
        self.sign_in_lbl.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.username_in_input = QLineEdit(self.sign_up_in_widget)
        self.username_in_input.setObjectName("username_in_input")
        self.username_in_input.setGeometry(QRect(500, 150, 191, 27))
        self.username_in_lbl = QLabel(self.sign_up_in_widget)
        self.username_in_lbl.setObjectName("username_in_lbl")
        self.username_in_lbl.setGeometry(QRect(500, 100, 200, 25))
        self.username_in_lbl.setFont(font)
        self.username_in_lbl.setStyleSheet("color: white;")
        self.sign_in_btn = QPushButton(self.sign_up_in_widget)
        self.sign_in_btn.setObjectName("sign_in_btn")
        self.sign_in_btn.setGeometry(QRect(500, 430, 231, 51))
        self.sign_in_btn.setFont(font1)
        self.sign_in_btn.setStyleSheet(
            "background-color: rgb(47, 47, 47); color: white;"
        )
        self.sign_in_btn.setCheckable(True)
        self.sign_in_btn.setAutoExclusive(True)
        self.password_in_lb = QLabel(self.sign_up_in_widget)
        self.password_in_lb.setObjectName("password_in_lb")
        self.password_in_lb.setGeometry(QRect(500, 210, 200, 25))
        self.password_in_lb.setFont(font)
        self.password_in_lb.setStyleSheet("color: white;")
        self.stay_logged_cb = QCheckBox(self.sign_up_in_widget)
        self.stay_logged_cb.setObjectName("stay_logged_cb")
        self.stay_logged_cb.setGeometry(QRect(500, 320, 191, 25))
        self.main_widget.addWidget(self.sign_up_in_widget)
        self.todo_widget = QWidget()
        self.todo_widget.setObjectName("todo_widget")
        self.add_item_lbl = QLabel(self.todo_widget)
        self.add_item_lbl.setObjectName("add_item_lbl")
        self.add_item_lbl.setGeometry(QRect(40, 30, 121, 25))
        self.add_item_lbl.setFont(font2)
        self.add_item_lbl.setStyleSheet("color: white;")
        self.add_item_btn = QPushButton(self.todo_widget)
        self.add_item_btn.setObjectName("add_item_btn")
        self.add_item_btn.setGeometry(QRect(40, 430, 261, 51))
        self.add_item_btn.setFont(font1)
        self.add_item_btn.setStyleSheet(
            "background-color: rgb(47, 47, 47); color: white;"
        )
        self.add_item_btn.setCheckable(True)
        self.add_item_btn.setAutoExclusive(True)
        self.item_txt = QLineEdit(self.todo_widget)
        self.item_txt.setObjectName("item_txt")
        self.item_txt.setGeometry(QRect(40, 120, 261, 241))
        self.item_txt.setFont(font)
        self.priority_spinbox = QSpinBox(self.todo_widget)
        self.priority_spinbox.setObjectName("priority_spinbox")
        self.priority_spinbox.setGeometry(QRect(153, 380, 141, 27))
        self.priority_spinbox.setFont(font)
        self.item_txt_lbl = QLabel(self.todo_widget)
        self.item_txt_lbl.setObjectName("item_txt_lbl")
        self.item_txt_lbl.setGeometry(QRect(40, 80, 161, 25))
        self.item_txt_lbl.setFont(font)
        self.item_txt_lbl.setStyleSheet("color: white;")
        self.priority_lbl = QLabel(self.todo_widget)
        self.priority_lbl.setObjectName("priority_lbl")
        self.priority_lbl.setGeometry(QRect(40, 380, 91, 25))
        self.priority_lbl.setFont(font)
        self.priority_lbl.setStyleSheet("color: white;")
        self.todo_listwidget = QListWidget(self.todo_widget)
        self.todo_listwidget.setObjectName("todo_listwidget")
        self.todo_listwidget.setGeometry(QRect(380, 30, 361, 451))
        self.main_widget.addWidget(self.todo_widget)
        self.quiz_widget = QWidget()
        self.quiz_widget.setObjectName("quiz_widget")
        self.quiz_stacked_widget = QStackedWidget(self.quiz_widget)
        self.quiz_stacked_widget.setObjectName("quiz_stacked_widget")
        self.quiz_stacked_widget.setGeometry(QRect(0, 0, 811, 511))
        self.params_widget = QWidget()
        self.params_widget.setObjectName("params_widget")
        self.param_lbl = QLabel(self.params_widget)
        self.param_lbl.setObjectName("param_lbl")
        self.param_lbl.setGeometry(QRect(40, 30, 701, 31))
        sizePolicy.setHeightForWidth(self.param_lbl.sizePolicy().hasHeightForWidth())
        self.param_lbl.setSizePolicy(sizePolicy)
        self.param_lbl.setBaseSize(QSize(0, 0))
        self.param_lbl.setFont(font2)
        self.param_lbl.setStyleSheet("color: white;")
        self.param_lbl.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.file_lbl = QLabel(self.params_widget)
        self.file_lbl.setObjectName("file_lbl")
        self.file_lbl.setGeometry(QRect(40, 100, 250, 25))
        sizePolicy.setHeightForWidth(self.file_lbl.sizePolicy().hasHeightForWidth())
        self.file_lbl.setSizePolicy(sizePolicy)
        self.file_lbl.setBaseSize(QSize(0, 0))
        self.file_lbl.setFont(font)
        self.file_lbl.setStyleSheet("color: white;")
        self.file_lbl.setAlignment(
            Qt.AlignmentFlag.AlignLeading
            | Qt.AlignmentFlag.AlignLeft
            | Qt.AlignmentFlag.AlignVCenter
        )
        self.score_lbl = QLabel(self.params_widget)
        self.score_lbl.setObjectName("score_lbl")
        self.score_lbl.setGeometry(QRect(40, 220, 250, 25))
        sizePolicy.setHeightForWidth(self.score_lbl.sizePolicy().hasHeightForWidth())
        self.score_lbl.setSizePolicy(sizePolicy)
        self.score_lbl.setBaseSize(QSize(0, 0))
        self.score_lbl.setFont(font)
        self.score_lbl.setStyleSheet("color: white;")
        self.score_lbl.setAlignment(
            Qt.AlignmentFlag.AlignLeading
            | Qt.AlignmentFlag.AlignLeft
            | Qt.AlignmentFlag.AlignVCenter
        )
        self.answer_lbl = QLabel(self.params_widget)
        self.answer_lbl.setObjectName("answer_lbl")
        self.answer_lbl.setGeometry(QRect(40, 330, 250, 25))
        sizePolicy.setHeightForWidth(self.answer_lbl.sizePolicy().hasHeightForWidth())
        self.answer_lbl.setSizePolicy(sizePolicy)
        self.answer_lbl.setBaseSize(QSize(0, 0))
        self.answer_lbl.setFont(font)
        self.answer_lbl.setStyleSheet("color: white;")
        self.answer_lbl.setAlignment(
            Qt.AlignmentFlag.AlignLeading
            | Qt.AlignmentFlag.AlignLeft
            | Qt.AlignmentFlag.AlignVCenter
        )
        self.random_q_order_lbl = QLabel(self.params_widget)
        self.random_q_order_lbl.setObjectName("random_q_order_lbl")
        self.random_q_order_lbl.setGeometry(QRect(490, 220, 251, 25))
        sizePolicy.setHeightForWidth(
            self.random_q_order_lbl.sizePolicy().hasHeightForWidth()
        )
        self.random_q_order_lbl.setSizePolicy(sizePolicy)
        self.random_q_order_lbl.setBaseSize(QSize(0, 0))
        self.random_q_order_lbl.setFont(font)
        self.random_q_order_lbl.setStyleSheet("color: white;")
        self.random_q_order_lbl.setAlignment(
            Qt.AlignmentFlag.AlignLeading
            | Qt.AlignmentFlag.AlignLeft
            | Qt.AlignmentFlag.AlignVCenter
        )
        self.random_ans_order_lbl = QLabel(self.params_widget)
        self.random_ans_order_lbl.setObjectName("random_ans_order_lbl")
        self.random_ans_order_lbl.setGeometry(QRect(490, 100, 251, 25))
        sizePolicy.setHeightForWidth(
            self.random_ans_order_lbl.sizePolicy().hasHeightForWidth()
        )
        self.random_ans_order_lbl.setSizePolicy(sizePolicy)
        self.random_ans_order_lbl.setBaseSize(QSize(0, 0))
        self.random_ans_order_lbl.setFont(font)
        self.random_ans_order_lbl.setStyleSheet("color: white;")
        self.random_ans_order_lbl.setAlignment(
            Qt.AlignmentFlag.AlignLeading
            | Qt.AlignmentFlag.AlignLeft
            | Qt.AlignmentFlag.AlignVCenter
        )
        self.file_input = QComboBox(self.params_widget)
        self.file_input.setObjectName("file_input")
        self.file_input.setGeometry(QRect(40, 150, 251, 31))
        self.file_input.setStyleSheet("color: White;")
        self.aeq_rbtn = QRadioButton(self.params_widget)
        self.aeq_rbtn.setObjectName("aeq_rbtn")
        self.aeq_rbtn.setGeometry(QRect(40, 270, 151, 25))
        self.aeq_rbtn.setStyleSheet("color:white;")
        self.ate_rbtn = QRadioButton(self.params_widget)
        self.ate_rbtn.setObjectName("ate_rbtn")
        self.ate_rbtn.setGeometry(QRect(240, 270, 131, 25))
        self.ate_rbtn.setStyleSheet("color:white;")
        self.say_rbtn = QRadioButton(self.params_widget)
        self.say_rbtn.setObjectName("say_rbtn")
        self.say_rbtn.setGeometry(QRect(40, 380, 50, 25))
        self.say_rbtn.setStyleSheet("color:white;")
        self.san_rbtn = QRadioButton(self.params_widget)
        self.san_rbtn.setObjectName("san_rbtn")
        self.san_rbtn.setGeometry(QRect(120, 380, 50, 25))
        self.san_rbtn.setStyleSheet("color:white;")
        self.raon_rbtn = QRadioButton(self.params_widget)
        self.raon_rbtn.setObjectName("raon_rbtn")
        self.raon_rbtn.setGeometry(QRect(570, 150, 50, 25))
        self.raon_rbtn.setStyleSheet("color:white;")
        self.raoy_rbtn = QRadioButton(self.params_widget)
        self.raoy_rbtn.setObjectName("raoy_rbtn")
        self.raoy_rbtn.setGeometry(QRect(490, 150, 50, 25))
        self.raoy_rbtn.setStyleSheet("color:white;")
        self.rqoy_rbtn = QRadioButton(self.params_widget)
        self.rqoy_rbtn.setObjectName("rqoy_rbtn")
        self.rqoy_rbtn.setGeometry(QRect(490, 270, 50, 25))
        self.rqoy_rbtn.setStyleSheet("color:white;")
        self.rqon_rbtn = QRadioButton(self.params_widget)
        self.rqon_rbtn.setObjectName("rqon_rbtn")
        self.rqon_rbtn.setGeometry(QRect(570, 270, 50, 25))
        self.rqon_rbtn.setStyleSheet("color:white;")
        self.quiz_stacked_widget.addWidget(self.params_widget)
        self.question_widget = QWidget()
        self.question_widget.setObjectName("question_widget")
        self.quiz_stacked_widget.addWidget(self.question_widget)
        self.main_widget.addWidget(self.quiz_widget)
        self.home_widget = QWidget()
        self.home_widget.setObjectName("home_widget")
        self.overall_activity_lbl = QLabel(self.home_widget)
        self.overall_activity_lbl.setObjectName("overall_activity_lbl")
        self.overall_activity_lbl.setGeometry(QRect(20, 30, 200, 25))
        self.overall_activity_lbl.setFont(font)
        self.overall_activity_lbl.setStyleSheet("color: white;")
        self.week_activity_lbl = QLabel(self.home_widget)
        self.week_activity_lbl.setObjectName("week_activity_lbl")
        self.week_activity_lbl.setGeometry(QRect(20, 280, 200, 25))
        sizePolicy.setHeightForWidth(
            self.week_activity_lbl.sizePolicy().hasHeightForWidth()
        )
        self.week_activity_lbl.setSizePolicy(sizePolicy)
        self.week_activity_lbl.setBaseSize(QSize(0, 0))
        self.week_activity_lbl.setFont(font)
        self.week_activity_lbl.setStyleSheet("color: white;")
        self.to_do_lbl = QLabel(self.home_widget)
        self.to_do_lbl.setObjectName("to_do_lbl")
        self.to_do_lbl.setGeometry(QRect(450, 280, 200, 25))
        self.to_do_lbl.setFont(font)
        self.to_do_lbl.setStyleSheet("color: white;")
        self.overall_activity_widget = QWidget(self.home_widget)
        self.overall_activity_widget.setObjectName("overall_activity_widget")
        self.overall_activity_widget.setGeometry(QRect(20, 70, 731, 180))
        self.week_activity_widget = QWidget(self.home_widget)
        self.week_activity_widget.setObjectName("week_activity_widget")
        self.week_activity_widget.setGeometry(QRect(20, 320, 391, 180))
        self.to_do_list_widget = QWidget(self.home_widget)
        self.to_do_list_widget.setObjectName("to_do_list_widget")
        self.to_do_list_widget.setGeometry(QRect(450, 320, 301, 171))
        self.main_widget.addWidget(self.home_widget)
        self.second_brain_widget = QWidget()
        self.second_brain_widget.setObjectName("second_brain_widget")
        self.main_widget.addWidget(self.second_brain_widget)
        self.spaced_repetition_widget = QWidget()
        self.spaced_repetition_widget.setObjectName("spaced_repetition_widget")
        self.main_widget.addWidget(self.spaced_repetition_widget)
        self.active_recall_widget = QWidget()
        self.active_recall_widget.setObjectName("active_recall_widget")
        self.main_widget.addWidget(self.active_recall_widget)
        self.incremental_reading_widget = QWidget()
        self.incremental_reading_widget.setObjectName("incremental_reading_widget")
        self.main_widget.addWidget(self.incremental_reading_widget)
        self.pomodoro_widget = QWidget()
        self.pomodoro_widget.setObjectName("pomodoro_widget")
        self.main_widget.addWidget(self.pomodoro_widget)

        self.retranslateUi(Form)

        self.main_widget.setCurrentIndex(1)

        QMetaObject.connectSlotsByName(Form)

    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", "Learning App", None))
        self.menu_lbl.setText(QCoreApplication.translate("Form", "Strategies", None))
        self.spaced_repetition_btn.setText(
            QCoreApplication.translate("Form", "Spaced Repetition", None)
        )
        self.active_recall_btn.setText(
            QCoreApplication.translate("Form", "Active Recall", None)
        )
        self.incremental_reading_btn.setText(
            QCoreApplication.translate("Form", "Incremental Reading", None)
        )
        self.home_btn.setText(QCoreApplication.translate("Form", "Home", None))
        self.pomodoro_btn.setText(QCoreApplication.translate("Form", "Pomodoro", None))
        self.quiz_btn.setText(QCoreApplication.translate("Form", "Quiz", None))
        self.second_brain_btn.setText(
            QCoreApplication.translate("Form", "Second Brain", None)
        )
        self.to_do_btn.setText(QCoreApplication.translate("Form", "To-Do List", None))
        self.sign_in_out_btn.setText(
            QCoreApplication.translate("Form", "Sign Up or Sign In", None)
        )
        self.log_out_btn.setText(QCoreApplication.translate("Form", "Log Out", None))
        self.profile_btn.setText(QCoreApplication.translate("Form", "Profile", None))
        self.username_up_lbl.setText(
            QCoreApplication.translate("Form", "Username", None)
        )
        self.password_up_lbl.setText(
            QCoreApplication.translate("Form", "Password", None)
        )
        self.sign_up_lbl.setText(QCoreApplication.translate("Form", "Sign Up", None))
        self.sign_up_btn.setText(QCoreApplication.translate("Form", "Sign Up", None))
        self.confirm_password_lbl.setText(
            QCoreApplication.translate("Form", "Confirm password", None)
        )
        self.sign_in_lbl.setText(QCoreApplication.translate("Form", "Sign In", None))
        self.username_in_lbl.setText(
            QCoreApplication.translate("Form", "Username", None)
        )
        self.sign_in_btn.setText(QCoreApplication.translate("Form", "Sign In", None))
        self.password_in_lb.setText(
            QCoreApplication.translate("Form", "Password", None)
        )
        self.stay_logged_cb.setText(
            QCoreApplication.translate("Form", "Stay logged", None)
        )
        self.add_item_lbl.setText(QCoreApplication.translate("Form", "Add item", None))
        self.add_item_btn.setText(QCoreApplication.translate("Form", "Add", None))
        self.item_txt_lbl.setText(
            QCoreApplication.translate("Form", "Item description:", None)
        )
        self.priority_lbl.setText(QCoreApplication.translate("Form", "Priority:", None))
        self.param_lbl.setText(QCoreApplication.translate("Form", "Parameters", None))
        self.file_lbl.setText(QCoreApplication.translate("Form", "File", None))
        self.score_lbl.setText(QCoreApplication.translate("Form", "Show score", None))
        self.answer_lbl.setText(QCoreApplication.translate("Form", "Show answer", None))
        self.random_q_order_lbl.setText(
            QCoreApplication.translate("Form", "Randomized quesion order", None)
        )
        self.random_ans_order_lbl.setText(
            QCoreApplication.translate("Form", "Randomized answer order", None)
        )
        self.aeq_rbtn.setText(
            QCoreApplication.translate("Form", "After each question", None)
        )
        self.ate_rbtn.setText(
            QCoreApplication.translate("Form", "At the end only", None)
        )
        self.say_rbtn.setText(QCoreApplication.translate("Form", "Yes", None))
        self.san_rbtn.setText(QCoreApplication.translate("Form", "No", None))
        self.raon_rbtn.setText(QCoreApplication.translate("Form", "No", None))
        self.raoy_rbtn.setText(QCoreApplication.translate("Form", "Yes", None))
        self.rqoy_rbtn.setText(QCoreApplication.translate("Form", "Yes", None))
        self.rqon_rbtn.setText(QCoreApplication.translate("Form", "No", None))
        self.overall_activity_lbl.setText(
            QCoreApplication.translate("Form", "Overall Activity", None)
        )
        self.week_activity_lbl.setText(
            QCoreApplication.translate("Form", "This Week Activity", None)
        )
        self.to_do_lbl.setText(QCoreApplication.translate("Form", "To-Do List", None))

    # retranslateUi
